// GENERATED by `scripts/gen-contribution-slots.mjs`, do not edit.
//
// The sdk-leaf mirror of every first-party (packages/components-owned)
// `ContributionRegistry` slot declaration, generated from the widgets' own
// `declare module "@ksp-gonogo/core"` blocks so a facade-sealed Uplink
// (whose program can only see files reachable from this package) types its
// `registerContribution` calls against the exact same contract. See the
// generator's header for the package-graph reasoning, and
// `../api/slots.ts` for the augment-side precedent it mirrors.

import type { FilterEntry } from "../api/types";
import type { IsruConverterEntry, IsruDrillEntry } from "./contract";

/** Mirrors `MeterTone` (`packages/ui-kit/src/Meter.tsx`). */
export type MeterTone = "neutral" | "go" | "warn" | "nogo" | "info";

/** Mirrors `ResourceOpsUnit` (`packages/components/src/ResourceOps/unit.ts`). */
export type ResourceOpsUnit =
  | { kind: "drill"; drill: IsruDrillEntry }
  | { kind: "converter"; converter: IsruConverterEntry };

/** Mirrors `ShipMapPartMetaEntry` (`packages/components/src/ShipMap/shipTopology.ts`). */
export interface ShipMapPartMetaEntry {
  /** `ShipMapPart.flightId`, stringified (see `ShipMapPartMeterEntry.partId`). */
  partId: string;
  /** Short label, e.g. "Water Recycler". Doubles as part of this row's
   *  identity: a contributor should emit at most one entry per (partId,
   *  label) pair. */
  label: string;
  tone: MeterTone;
  /**
   * "ratio": a 0..1 reading, rendered as a `<Meter>` (reserved: see the
   * interface doc above, nothing emits this today). "text": a free-form
   * status string, rendered as a plain label/value row (fitted-process
   * running/broken/idle state today).
   */
  kind: "ratio" | "text";
  /** Present when `kind === "ratio"`. */
  value?: number;
  /** Present when `kind === "text"`. */
  text?: string;
}

/** Mirrors `ShipMapPartMeterEntry` (`packages/components/src/ShipMap/shipTopology.ts`). */
export interface ShipMapPartMeterEntry {
  /**
   * `ShipMapPart.flightId`, stringified: contribution entries travel through
   * the generic per-slot aggregation store as plain data, so the key stays a
   * string rather than baking in a numeric-vs-string identity assumption.
   */
  partId: string;
  /** Resource name exactly as it appears on `vessel.parts` (e.g.
   *  "LiquidFuel", "Water"). Doubles as part of this meter's identity: a
   *  contributor should emit at most one entry per (partId, resource) pair.
   *  Also the renderer's key into `resourceColor` for the fill's identity
   *  colour, see this interface's own doc comment. */
  resource: string;
  /** Human label. Falls back to `resource` when the contributor has no nicer
   *  name (the built-in five don't; a Kerbalism profile's
   *  `KerbalismResourceDef.displayName` does). */
  displayName: string;
  /** Current stored amount, resource units. */
  amount: number;
  /** Max storage capacity, resource units. A renderer drops any entry with
   *  `capacity <= 0` (nothing to fill), the same guard the old hardcoded
   *  `renderResourceFill` applied. */
  capacity: number;
  /**
   * A SEPARATE status signal, never the fill hue: `"critical"` /
   * `"low"` draw a border tint or badge alongside the identity-coloured
   * fill; `null`/`undefined` means healthy, no status signal drawn. A
   * contributor decides its own low/critical thresholds (a Kerbalism
   * profile's `lowThreshold`, or the built-in contribution's own ratio
   * cutoffs); ShipMap only renders whichever of the two levels it's given.
   */
  status?: "low" | "critical" | null;
}

declare module "../api/types" {
  interface ContributionRegistry {
    "resource-ops.filters": {
      entry: FilterEntry<ResourceOpsUnit>;
      topics: "isru.drills" | "isru.converters";
    };
    "ship-map.part-meta": {
      entry: ShipMapPartMetaEntry;
      topics: "kerbalism.lifesupport" | "kerbalism.profile";
    };
    "ship-map.part-meters": {
      entry: ShipMapPartMeterEntry;
      topics: "vessel.parts" | "kerbalism.profile";
    };
  }
}
