import { getDataSources } from "@gonogo/core";
import { useEffect, useRef } from "react";
import styled from "styled-components";
import {
  ComponentOverlay,
  OverlayProvider,
} from "../components/ComponentOverlay";
import type { DashboardConfig, DashboardHandle } from "../components/Dashboard";
import { Dashboard } from "../components/Dashboard";

const DEMO_CONFIG: DashboardConfig = {
  items: [
    { i: "status", componentId: "data-source-status" },
    {
      i: "ag-sas",
      componentId: "action-group",
      config: { actionGroupId: "SAS" },
    },
    {
      i: "ag-rcs",
      componentId: "action-group",
      config: { actionGroupId: "RCS" },
    },
    {
      i: "ag-gear",
      componentId: "action-group",
      config: { actionGroupId: "Gear" },
    },
    {
      i: "ag-brake",
      componentId: "action-group",
      config: { actionGroupId: "Brake" },
    },
    {
      i: "ag-light",
      componentId: "action-group",
      config: { actionGroupId: "Light" },
    },
    {
      i: "ag-ag1",
      componentId: "action-group",
      config: { actionGroupId: "AG1" },
    },
    { i: "orbit", componentId: "current-orbit" },
    { i: "orbit-view", componentId: "orbit-view" },
    { i: "target", componentId: "distance-to-target" },
    { i: "map", componentId: "map-view" },
    { i: "kos", componentId: "kos-terminal" },
    {
      i: "kos-ro",
      componentId: "kos-terminal",
      config: { readOnly: true, cpuName: "system" },
    },
  ],

  layouts: {
    lg: [
      {
        w: 8,
        h: 6,
        x: 0,
        y: 0,
        i: "status",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 8,
        y: 3,
        i: "ag-sas",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 11,
        y: 3,
        i: "ag-rcs",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 14,
        y: 0,
        i: "ag-gear",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 14,
        y: 3,
        i: "ag-brake",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 8,
        y: 0,
        i: "ag-light",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 11,
        y: 0,
        i: "ag-ag1",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 6,
        x: 17,
        y: 0,
        i: "orbit",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 6,
        x: 22,
        y: 0,
        i: "orbit-view",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 3,
        x: 6,
        y: 24,
        i: "target",
        moved: false,
        static: false,
      },
      {
        w: 26,
        h: 18,
        x: 0,
        y: 6,
        i: "map",
        moved: false,
        static: false,
      },
      {
        w: 10,
        h: 24,
        x: 26,
        y: 0,
        i: "kos",
        moved: false,
        static: false,
      },
      {
        w: 24,
        h: 16,
        x: 6,
        y: 27,
        i: "kos-ro",
        moved: false,
        static: false,
      },
    ],
    md: [
      {
        w: 10,
        h: 1,
        x: 0,
        y: 0,
        i: "status",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 1,
        i: "ag-sas",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 2,
        y: 1,
        i: "ag-rcs",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 4,
        y: 1,
        i: "ag-gear",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 6,
        y: 1,
        i: "ag-brake",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 8,
        y: 1,
        i: "ag-light",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 3,
        i: "ag-ag1",
        moved: false,
        static: false,
      },
      {
        w: 4,
        h: 6,
        x: 0,
        y: 5,
        i: "orbit",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 6,
        x: 4,
        y: 3,
        i: "orbit-view",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 7,
        y: 3,
        i: "target",
        moved: false,
        static: false,
      },
      {
        w: 10,
        h: 5,
        x: 0,
        y: 11,
        i: "map",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 5,
        x: 0,
        y: 16,
        i: "kos",
        moved: false,
        static: false,
      },
      {
        w: 5,
        h: 5,
        x: 5,
        y: 16,
        i: "kos-ro",
        moved: false,
        static: false,
      },
    ],
    sm: [
      {
        w: 6,
        h: 1,
        x: 0,
        y: 0,
        i: "status",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 1,
        i: "ag-sas",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 2,
        y: 1,
        i: "ag-rcs",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 4,
        y: 1,
        i: "ag-gear",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 3,
        i: "ag-brake",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 2,
        y: 3,
        i: "ag-light",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 4,
        y: 3,
        i: "ag-ag1",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 6,
        x: 0,
        y: 5,
        i: "orbit",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 6,
        x: 3,
        y: 5,
        i: "orbit-view",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 0,
        y: 11,
        i: "target",
        moved: false,
        static: false,
      },
      {
        w: 6,
        h: 5,
        x: 0,
        y: 14,
        i: "map",
        moved: false,
        static: false,
      },
      {
        w: 6,
        h: 5,
        x: 0,
        y: 19,
        i: "kos",
        moved: false,
        static: false,
      },
      {
        w: 6,
        h: 5,
        x: 0,
        y: 24,
        i: "kos-ro",
        moved: false,
        static: false,
      },
    ],
    xs: [
      {
        w: 6,
        h: 1,
        x: 0,
        y: 0,
        i: "status",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 1,
        i: "ag-sas",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 2,
        y: 1,
        i: "ag-rcs",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 4,
        y: 1,
        i: "ag-gear",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 3,
        i: "ag-brake",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 2,
        y: 3,
        i: "ag-light",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 4,
        y: 3,
        i: "ag-ag1",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 6,
        x: 0,
        y: 5,
        i: "orbit",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 6,
        x: 3,
        y: 5,
        i: "orbit-view",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 0,
        y: 11,
        i: "target",
        moved: false,
        static: false,
      },
      {
        w: 6,
        h: 5,
        x: 0,
        y: 14,
        i: "map",
        moved: false,
        static: false,
      },
      {
        w: 12,
        h: 14,
        x: 0,
        y: 19,
        i: "kos",
        moved: false,
        static: false,
      },
      {
        w: 6,
        h: 5,
        x: 0,
        y: 33,
        i: "kos-ro",
        moved: false,
        static: false,
      },
    ],
    xxs: [
      {
        w: 6,
        h: 1,
        x: 0,
        y: 0,
        i: "status",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 1,
        i: "ag-sas",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 2,
        y: 1,
        i: "ag-rcs",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 4,
        y: 1,
        i: "ag-gear",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 0,
        y: 3,
        i: "ag-brake",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 2,
        y: 3,
        i: "ag-light",
        moved: false,
        static: false,
      },
      {
        w: 2,
        h: 2,
        x: 4,
        y: 3,
        i: "ag-ag1",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 6,
        x: 0,
        y: 5,
        i: "orbit",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 6,
        x: 3,
        y: 5,
        i: "orbit-view",
        moved: false,
        static: false,
      },
      {
        w: 3,
        h: 3,
        x: 0,
        y: 11,
        i: "target",
        moved: false,
        static: false,
      },
      {
        w: 6,
        h: 5,
        x: 0,
        y: 14,
        i: "map",
        moved: false,
        static: false,
      },
      {
        w: 6,
        h: 5,
        x: 0,
        y: 19,
        i: "kos",
        moved: false,
        static: false,
      },
      {
        w: 6,
        h: 5,
        x: 0,
        y: 24,
        i: "kos-ro",
        moved: false,
        static: false,
      },
    ],
  },
};

// ---------------------------------------------------------------------------
// Screen
// ---------------------------------------------------------------------------

export function MainScreen() {
  const dashboardRef = useRef<DashboardHandle>(null);

  useEffect(() => {
    const sources = getDataSources();
    sources.forEach((s) => {
      void s.connect();
    });
    return () => {
      sources.forEach((s) => {
        s.disconnect();
      });
    };
  }, []);

  const addItem: OverlayProvider_AddItem = (item, layout) => {
    dashboardRef.current?.addItem(item, layout);
  };

  const currentLayouts = dashboardRef.current?.currentLayouts ?? { lg: [] };

  return (
    <OverlayProvider addItem={addItem}>
      <Layout>
        <Dashboard
          ref={dashboardRef}
          config={DEMO_CONFIG}
          storageKey="gonogo:dashboard:main"
        />
        <ComponentOverlay currentLayouts={currentLayouts} />
      </Layout>
    </OverlayProvider>
  );
}

// Inline type alias to avoid importing DashboardItem directly here
type OverlayProvider_AddItem = (
  item: import("../components/Dashboard").DashboardItem,
  layout: { x: number; y: number; w: number; h: number },
) => void;

const Layout = styled.div`
  padding: 24px;
  background: #050505;
  min-height: 100vh;
`;
