// GENERATED by `scripts/emit-slot-manifest.ts`. Do not edit.
//
// Every slot instance the first-party widgets actually mounted when the probe
// harness rendered them. Nobody writes this by hand and nobody has to keep it
// in sync: it is a recording of what the render tree did, taken from the live
// slot-instance registry rather than parsed out of source.
//
// It is also OPTIONAL. Delete this file and every slot still works, addressed
// through `slot(Component, widget, name)`; what is lost is only the compiler
// knowing which instance names exist.

declare module "../types" {
  interface WidgetSlotManifest {
    "resource-ops": {
      filter: "process" | "resource";
    };
    "ship-map": {
      meter: "supplies";
    };
  }
}

// Load-bearing: makes this file a MODULE, without which TS rejects the relative
// `declare module` specifier above as an ambient declaration.
export {};
