// ---------------------------------------------------------------------------
// The whole of the codegen. It parses nothing: the slot instances come from the
// live registry after something has rendered every widget, so what it emits is a
// recording of what the render tree actually did rather than a guess made by
// reading source.
//
// Where the render comes from: the visual-gate probe harness
// (`packages/components/scripts/visual-gate.ts`) already mounts every widget in
// a real browser. Dumping `dumpSlotManifest()` from that page is the whole
// integration, and gating it works exactly like the visual baselines do: the
// committed file is a baseline, a mismatch fails CI and names the drift, and a
// flag regenerates it.
// ---------------------------------------------------------------------------

const HEADER = `// GENERATED by \`scripts/emit-slot-manifest.ts\`. Do not edit.
//
// Every slot instance the first-party widgets actually mounted when the probe
// harness rendered them. Nobody writes this by hand and nobody has to keep it
// in sync: it is a recording of what the render tree did, taken from the live
// slot-instance registry rather than parsed out of source.
//
// It is also OPTIONAL. Delete this file and every slot still works, addressed
// through \`slot(Component, widget, name)\`; what is lost is only the compiler
// knowing which instance names exist.
`;

/** Deterministic, so a re-run with no change is a no-op diff. */
export function emitSlotManifest(
  dump: Record<string, Record<string, string[]>>,
): string {
  const widgets = Object.keys(dump).sort();
  const body = widgets
    .map((widgetId) => {
      const components = Object.keys(dump[widgetId] ?? {}).sort();
      const lines = components.map((componentId) => {
        const names = [...new Set(dump[widgetId]?.[componentId] ?? [])]
          .sort()
          .map((name) => JSON.stringify(name))
          .join(" | ");
        return `      ${componentId}: ${names};`;
      });
      return [`    ${JSON.stringify(widgetId)}: {`, ...lines, "    };"].join(
        "\n",
      );
    })
    .join("\n");

  return `${HEADER}
declare module "../types" {
  interface WidgetSlotManifest {
${body}
  }
}

// Load-bearing: makes this file a MODULE, without which TS rejects the relative
// \`declare module\` specifier above as an ambient declaration.
export {};
`;
}
